version: "3"

services:
  server:
    image: docker.io/buddsme/tutoring-calendar:v1
    container_name: "java-api"
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tutoring_calendar?verifyServerCertificate=false&useSSL=true&&requireSSL=true&serverTimezone=UTC
    networks:
      - springmysql-net
    volumes:
      - ./:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=artem
      - MYSQL_DATABASE=tutoring_calendar
      - MYSQL_PASSWORD=artem
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

networks:
  springmysql-net:

volumes:
  mysql_data:
  mysql_config:
